spring.application.name=book-library

# SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=book_library;encrypt=false;trustServerCertificate=true
spring.datasource.username=book_app
spring.datasource.password=AplicacaoBookLibrary
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Flyway
spring.flyway.enabled=false